# Generated by Django 5.2.12 on 2026-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0002_messagelog_last_attempt_at_messagelog_max_retries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="to_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")], default="email", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="to_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
