# Generated by Django 5.2.12 on 2026-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0003_messagelog_to_phone_alter_messagelog_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="USD", max_length=8),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=8),
        ),
    ]
