# Generated by Django 5.2.12 on 2026-03-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_alter_invoice_currency_alter_payment_currency'),
        ('tenancy', '0003_tenant_currency_tenant_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_archived'], name='ops_message_tenant__8b5446_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_message_template_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ResourceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('assignment_note', models.TextField(blank=True)),
                ('assignment_due_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resource_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_templates', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_archived'], name='ops_resourc_tenant__3ac6fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_resource_template_per_tenant')],
            },
        ),
    ]
