# Generated by Django 5.2.12 on 2026-03-13 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_messagetemplate_resourcetemplate'),
        ('tenancy', '0003_tenant_currency_tenant_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'is_archived'], name='ops_event_tenant__8550b2_idx'),
        ),
    ]
