# Generated by Django 5.2.12 on 2026-03-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_event_is_archived_event_ops_event_tenant__8550b2_idx'),
        ('tenancy', '0005_tenant_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='metadata',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='metadata',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='schedulerjobrun',
            old_name='metadata',
            new_name='extensions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
        migrations.RemoveField(
            model_name='family',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='occurrences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences_set', to='ops.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='family',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='familycontact',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('default_notes', models.TextField(blank=True)),
                ('default_extensions', models.JSONField(blank=True, default=dict)),
                ('default_items', models.JSONField(blank=True, default=list, help_text="List of dicts: [{'description': '...', 'unit_price_cents': 100}]")),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_archived'], name='ops_invoice_tenant__723b51_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_invoice_template_per_tenant')],
            },
        ),
    ]
