# Generated by Django 5.2.12 on 2026-03-08 13:34

import apps.tenancy.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["status"], name="tenancy_ten_status_4ae576_idx")],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("staff", "Staff"),
                            ("parent", "Parent"),
                            ("student", "Student"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_membership_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "status"], name="tenancy_mem_tenant__358acf_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tenant"), name="uniq_membership_user_tenant"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user",),
                        name="uniq_default_tenant_per_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[apps.tenancy.validators.validate_host_format],
                    ),
                ),
                (
                    "domain_type",
                    models.CharField(
                        choices=[
                            ("platform_subdomain", "Platform subdomain"),
                            ("custom_domain", "Custom domain"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="not_required",
                        max_length=16,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ssl_status",
                    models.CharField(
                        choices=[
                            ("unmanaged", "Unmanaged"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        default="unmanaged",
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "verification_status"],
                        name="tenancy_dom_tenant__bf45aa_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("tenant",),
                        name="uniq_primary_domain_per_tenant",
                    )
                ],
            },
        ),
    ]
