# Generated by Django 5.2.12 on 2026-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_auditlog_domain_ssl_error_domain_ssl_provisioned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="tenant",
            name="locale",
            field=models.CharField(default="en-us", max_length=16),
        ),
    ]
