# Generated by Django 5.2.12 on 2026-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_currency_tenant_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
