# Generated by Django 5.2.12 on 2026-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_membership_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
