# Generated by Django 5.2.12 on 2026-03-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0003_messagelog_to_phone_alter_messagelog_channel_and_more'),
        ('tenancy', '0002_auditlog_domain_ssl_error_domain_ssl_provisioned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_billing', models.BooleanField(default=True)),
                ('can_view_resources', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_links', to='ops.family')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_portal_access_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_links', to='ops.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_links', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user', 'is_active'], name='portal_port_tenant__232c1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('family__isnull', False), ('student__isnull', False), _connector='OR'), name='portal_access_requires_target'), models.UniqueConstraint(fields=('tenant', 'user', 'family', 'student'), name='uniq_portal_access_target')],
            },
        ),
    ]
