# Generated by Django 5.2.12 on 2026-03-08 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_auditlog_domain_ssl_error_domain_ssl_provisioned_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized"), ("paid", "Paid")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_periods",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                (
                    "layout",
                    models.CharField(
                        choices=[("landing", "Landing"), ("info", "Info"), ("contact", "Contact")],
                        default="info",
                        max_length=24,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=255)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("is_homepage", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_pages",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("external_url", models.URLField(blank=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_menu_items",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="growth.sitepage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=160)),
                ("primary_color", models.CharField(default="#1f2937", max_length=16)),
                ("secondary_color", models.CharField(default="#0ea5e9", max_length=16)),
                ("accent_color", models.CharField(default="#f59e0b", max_length=16)),
                ("font_family", models.CharField(default="system-ui", max_length=120)),
                ("logo_url", models.URLField(blank=True)),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.TextField(blank=True)),
                ("custom_css", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_theme",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherCompPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comp_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("per_lesson", "Per lesson"),
                            ("revenue_share", "Revenue share"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rate_cents", models.PositiveIntegerField(default=0)),
                ("revenue_share_bps", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_comp_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_comp_plans",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lessons_count", models.PositiveIntegerField(default=0)),
                ("lesson_minutes", models.PositiveIntegerField(default=0)),
                ("gross_cents", models.IntegerField(default=0)),
                ("adjustments_cents", models.IntegerField(default=0)),
                ("total_cents", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="growth.payrollperiod",
                    ),
                ),
                (
                    "comp_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_lines",
                        to="growth.teachercompplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_cents", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="growth.payrollline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payouts",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="growth_payr_tenant__adf685_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["tenant", "status", "start_date"], name="growth_payr_tenant__ed69dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "start_date", "end_date"), name="uniq_payroll_period_window"
            ),
        ),
        migrations.AddIndex(
            model_name="sitepage",
            index=models.Index(
                fields=["tenant", "is_published"], name="growth_site_tenant__9500f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitepage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="uniq_site_page_slug_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitepage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_homepage", True)),
                fields=("tenant",),
                name="uniq_homepage_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="sitemenuitem",
            index=models.Index(
                fields=["tenant", "is_visible", "order"], name="growth_site_tenant__67e448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachercompplan",
            index=models.Index(
                fields=["tenant", "teacher", "is_active"], name="growth_teac_tenant__2a49ee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachercompplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "teacher"),
                name="uniq_active_comp_plan_per_teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["tenant", "teacher"], name="growth_payr_tenant__8226c5_idx"),
        ),
        migrations.AddConstraint(
            model_name="payrollline",
            constraint=models.UniqueConstraint(
                fields=("period", "teacher"), name="uniq_payroll_line_period_teacher"
            ),
        ),
    ]
